# Copyright 2026 OLO Labs
# SPDX-License-Identifier: Apache-2.0
services:
  control:
    depends_on: !reset {}
    entrypoint: [/bin/sh, -c, '. /config/identity.env; exec java -jar /app/quarkus-run.jar']
    env_file:
      - path: ./env/.env.db
        format: raw
    volumes:
      - ./env:/external:ro
    networks: [backend, frontend]
    extra_hosts: ["host.docker.internal:host-gateway"]
  probe:
    networks: [backend, frontend]
    extra_hosts: ["host.docker.internal:host-gateway"]
