-- Copyright 2026 OLO Labs
-- SPDX-License-Identifier: Apache-2.0
ALTER TABLE control_audit DROP CONSTRAINT control_audit_operation_check;
ALTER TABLE control_audit ADD CONSTRAINT control_audit_operation_check CHECK (operation IN
 ('CREATE','UPDATE','DELETE','IMPORT','BUNDLE_PUBLISH','BUNDLE_ROLLBACK',
  'APPROVAL_CREATE','APPROVAL_DECIDE','APPROVAL_EXPIRE','APPROVAL_SPEND','PERMIT_CONSUME',
  'ENROLLMENT_CREATE','ENROLLMENT_APPROVE','ENROLLMENT_DENY','ENROLLMENT_CONSUME',
  'DEVICE_REVOKE','DEVICE_CHECK_IN','DEVICE_RENEW','DEVICE_APPROVE','DEVICE_DEAPPROVE','DEVICE_ENABLE','DEVICE_DISABLE','DEVICE_IDENTITY_RECOVER',
  'PACKAGE_RELEASE','PACKAGE_ASSIGN','ROLLOUT_ADVANCE','ARTIFACT_GRANT',
  'BUILDER_SAVE','BUILDER_TEST','BUILDER_LEASE','BUILDER_RESULT','BUILDER_SEAL','BUILDER_EXPORT',
  'VAULT_PUT','PASSWORD_CHANGE_REQUESTED','PASSWORD_CHANGED',
  'MCP_RECEIVED','MCP_DISPATCHED','MCP_RESULT','MCP_DONE','MCP_FAILED'));
