-- Copyright 2026 OLO Labs
-- SPDX-License-Identifier: Apache-2.0
-- External Quickstart uses the same encrypted vault and append-only audit boundary.
CREATE TABLE quickstart_vault(name TEXT PRIMARY KEY CHECK(length(name) BETWEEN 1 AND 128),cipher BYTEA NOT NULL CHECK(octet_length(cipher)<=32800));
GRANT SELECT,INSERT,UPDATE ON quickstart_vault TO toolgate_control_runtime;
ALTER TABLE control_audit ALTER COLUMN operation TYPE varchar(32);
ALTER TABLE control_audit DROP CONSTRAINT control_audit_operation_check;
ALTER TABLE control_audit ADD CONSTRAINT control_audit_operation_check CHECK (operation IN
 ('CREATE','UPDATE','DELETE','IMPORT','BUNDLE_PUBLISH','BUNDLE_ROLLBACK',
  'APPROVAL_CREATE','APPROVAL_DECIDE','APPROVAL_EXPIRE','APPROVAL_SPEND','PERMIT_CONSUME',
  'ENROLLMENT_CREATE','ENROLLMENT_APPROVE','ENROLLMENT_DENY','ENROLLMENT_CONSUME',
  'DEVICE_REVOKE','DEVICE_CHECK_IN','DEVICE_RENEW','PACKAGE_RELEASE','PACKAGE_ASSIGN','ROLLOUT_ADVANCE','ARTIFACT_GRANT',
  'BUILDER_SAVE','BUILDER_TEST','BUILDER_LEASE','BUILDER_RESULT','BUILDER_SEAL','BUILDER_EXPORT',
  'PASSWORD_CHANGE_REQUESTED','PASSWORD_CHANGED','VAULT_PUT'));
