// Copyright 2026 OLO Labs
// SPDX-License-Identifier: Apache-2.0
package io.ololabs.toolgate.control;
import io.ololabs.toolgate.control.application.*;
import io.ololabs.toolgate.control.adapter.*;
import io.ololabs.toolgate.control.domain.*;
import io.ololabs.toolgate.contracts.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.io.TempDir;
import static org.junit.jupiter.api.Assertions.*;
class EnterpriseVaultTest {
 @TempDir java.nio.file.Path temp;
 EnterpriseConformanceTest graph;PostgresStore store;DirectoryService.Actor admin;VaultService vault;
 @BeforeEach void setup(){graph=new EnterpriseConformanceTest();graph.graph();var all=new GroupSelection(List.of(),true);var ceiling=new EnterpriseScope(all,all,List.of(),true,Arrays.stream(ResourceKind.values()).map(k->new EnterpriseResourceRule(k,"",EnterpriseResourceMatch.ANY)).toList(),graph.conditions());var rules=Arrays.stream(EnterpriseGroupType.values()).map(k->new EnterpriseManagementRule(List.of("read","recover"),k,all,List.of(ceiling),graph.conditions())).toList();graph.add(Ids.Kind.ROLE,new ControlRole("test-recovery-role","Scoped administrator",true,1L,UserRole.SUPER_ADMIN,EnterpriseRoleType.MANAGEMENT,rules));graph.add(Ids.Kind.TEAM,new ControlTeam("test-recovery-team","Reviewed administrators",true,1L,List.of("admin"),List.of("test-recovery-role")));store=new PostgresStore(SqliteState.open(temp.resolve("vault.sqlite")),graph.codec);store.transaction(EnterpriseConformanceTest.TENANT,true,tx->{tx.save(tx.load(),graph.directory());return null;});admin=new DirectoryService.Actor(EnterpriseConformanceTest.TENANT,"a".repeat(64),true,false,"admin");vault=new VaultService(store,graph.codec,new byte[32]);}
 void put(Map<Ids.RecordId,Directory.Entry> entries,ControlRole role){var entry=graph.codec.entry(Ids.Kind.ROLE,graph.codec.json(role));entries.put(entry.id(),entry);}
 void authorize(){store.transaction(admin.tenant(),true,tx->{var before=tx.load();var entries=new HashMap<>(before.entries());var role=graph.codec.model(entries.get(Ids.Kind.ROLE.id("test-recovery-role")).document(),ControlRole.class);var rules=role.managementRules().stream().map(r->{var actions=new ArrayList<>(r.actions());actions.addAll(List.of("vault-read","vault-write"));return new EnterpriseManagementRule(actions,r.groupType(),r.groups(),r.grantableScopes(),r.conditions());}).toList();put(entries,new ControlRole(role.id(),role.name(),true,role.revision()+1,role.portalRole(),role.roleType(),rules));tx.save(before,new Directory(before.revision()+1,entries));return null;});}
 String write(String value){return graph.codec.json(new EnterpriseVaultWrite("provider/token",value,"tools-a","devices-a"));}
 @Test void portalAdministratorNeedsExplicitSecretPurposeManagement(){assertEquals(403,assertThrows(Failure.class,()->vault.write(admin,write("secret"),"key")).status());assertEquals(List.of(),graph.codec.model(vault.list(admin).body(),EnterpriseVaultPage.class).items());}
 @Test void exactRetryNeverChangesCiphertextAndConflictingSecretIsRejected(){authorize();var response=vault.write(admin,write("private-custody-value"),"key");assertEquals(201,response.status());String first=store.transaction(admin.tenant(),false,tx->tx.enterprise().secret("provider/token").cipher());assertFalse(first.contains("private-custody-value"));assertEquals(response,vault.write(admin,write("private-custody-value"),"key"));assertEquals(409,assertThrows(Failure.class,()->vault.write(admin,write("different"),"key")).status());assertEquals(first,store.transaction(admin.tenant(),false,tx->tx.enterprise().secret("provider/token").cipher()));assertEquals(1,graph.codec.model(vault.list(admin).body(),EnterpriseVaultPage.class).items().size());assertFalse(graph.codec.snapshot(admin.tenant(),store.transaction(admin.tenant(),false,tx->tx.load()),false).contains("private-custody-value"));}
 @Test void revocationHidesReferencesAndStopsCredentialReplacement(){authorize();vault.write(admin,write("private"),"key");store.transaction(admin.tenant(),true,tx->{var before=tx.load();var entries=new HashMap<>(before.entries());var role=graph.codec.model(entries.get(Ids.Kind.ROLE.id("test-recovery-role")).document(),ControlRole.class);put(entries,new ControlRole(role.id(),role.name(),false,role.revision()+1,role.portalRole(),role.roleType(),role.managementRules()));tx.save(before,new Directory(before.revision()+1,entries));return null;});assertEquals(List.of(),graph.codec.model(vault.list(admin).body(),EnterpriseVaultPage.class).items());assertEquals(403,assertThrows(Failure.class,()->vault.write(admin,write("replacement"),"next")).status());}
}
