// Copyright 2026 OLO Labs
// SPDX-License-Identifier: Apache-2.0
package io.ololabs.toolgate.control.application;
import io.ololabs.toolgate.control.domain.Ids;
import io.ololabs.toolgate.contracts.*;
import java.time.Clock;
import java.security.cert.X509Certificate;
import java.util.*;
import static io.ololabs.toolgate.control.application.BuilderStore.Kind.*;

/** Durable authoring and designated-client leases. Author code is only opaque validated data here. */
public final class BuilderService {
    private final Store store;private final Codec codec;private final FleetCrypto crypto;private final FleetService fleet;
    private final EndpointService endpoints;private final Clock clock;private final boolean enabled;private final Ids.TenantId tenant;private final String server;
    public BuilderService(Store store,Codec codec,FleetCrypto crypto,FleetService fleet,EndpointService endpoints,Clock clock,boolean enabled,String tenant,String server){this.store=store;this.codec=codec;this.crypto=crypto;this.fleet=fleet;this.endpoints=endpoints;this.clock=clock;this.enabled=enabled;this.tenant=new Ids.TenantId(tenant);this.server=Ids.valid(server);}
    private void available(){if(!enabled)throw Failure.unavailable();}
    private void admin(DirectoryService.Actor actor){available();actor.requireAdmin();if(!actor.tenant().equals(tenant))throw forbidden();}
    private static Failure forbidden(){return new Failure(ErrorCode.FORBIDDEN,403,"Builder request rejected");}
    private long now(Store.Session tx){long now=clock.millis();if(now<0||now>9007199254740991L-600000||tx.approvalClock(now)>now)throw Failure.unavailable();return now;}
    private void permission(Store.Session tx,DirectoryService.Actor actor,String action,BuilderDefinition definition){new ManagementAccess(codec).requireEntry(tx.load(),actor.userId(),action,codec.entry(Ids.Kind.TOOL,codec.json(definition.tool().authorizationProfile().tool())),clock.millis());}
    private boolean visible(Store.Session tx,DirectoryService.Actor actor,BuilderDefinition definition){try{permission(tx,actor,"read",definition);return true;}catch(Failure denied){if(denied.status()!=403)throw denied;return false;}}
    private Store.Reply reply(Object document,long revision){return new Store.Reply(200,codec.json(document),revision);}
    private BuilderDraft draft(Store.Session tx,String id){var row=tx.builder().get(DRAFT,Ids.valid(id));if(row==null)throw new Failure(ErrorCode.NOT_FOUND,404,"Draft not found");return codec.model(row.document(),BuilderDraft.class);}
    private List<BuilderStore.Row> jobs(Store.Session tx){var rows=new ArrayList<BuilderStore.Row>();String cursor="";while(rows.size()<256){var page=tx.builder().page(TEST,cursor,32);rows.addAll(page);if(page.size()<32)break;cursor=page.getLast().id();}return rows;}
    public Store.Reply drafts(DirectoryService.Actor actor,String cursor){admin(actor);if(cursor!=null)Ids.valid(cursor);return store.transaction(tenant,false,tx->{var rows=tx.builder().page(DRAFT,cursor==null?"":cursor,33);return reply(new BuilderDraftPage(rows.stream().limit(32).map(r->codec.model(r.document(),BuilderDraft.class)).filter(d->visible(tx,actor,d.definition())).toList(),rows.size()>32?rows.get(31).id():null),0);});}
    public Store.Reply save(DirectoryService.Actor actor,String body,String key,String requestId){
        admin(actor);Ids.valid(key);Ids.valid(requestId);var request=codec.model(body,BuilderDraftRequest.class);var document=BuilderValidation.validate(codec,request.definition(),false);var digest=DirectoryService.digest("builder.save\n"+body);
        return store.transaction(tenant,true,tx->{now(tx);permission(tx,actor,"build",request.definition());var replay=tx.replay(actor.id(),key,digest);if(replay!=null)return replay;var old=tx.builder().get(DRAFT,request.id());
            if(old==null?request.expectedRevision()!=0:old.revision()!=request.expectedRevision()||draft(tx,request.id()).sealed())throw Failure.conflict();
            if(old==null&&tx.builder().count(DRAFT)>=128)throw Failure.conflict();long revision=Math.addExact(request.expectedRevision(),1);if(revision>9007199254740991L)throw Failure.conflict();
            var result=new BuilderDraft(request.id(),revision,request.definition(),DirectoryService.digest(codec.json(request.definition())),false,document);tx.builder().save(DRAFT,new BuilderStore.Row(request.id(),revision,codec.json(result)),request.expectedRevision());
            tx.audit(actor.id(),"BUILDER_SAVE",request.id(),revision,requestId,digest);var response=reply(result,revision);tx.remember(actor.id(),key,digest,response);return response;});
    }
    public Store.Reply test(DirectoryService.Actor actor,String body,String key,String requestId){
        admin(actor);Ids.valid(key);Ids.valid(requestId);var request=codec.model(body,BuilderTestRequest.class);var digest=DirectoryService.digest("builder.test\n"+body);
        return store.transaction(tenant,true,tx->{long now=now(tx);permission(tx,actor,"build",draft(tx,request.draftId()).definition());endpoints.management(tx,actor,"build",request.deviceId());var replay=tx.replay(actor.id(),key,digest);if(replay!=null)return replay;tx.builder().prune(Math.max(0,now-604800000));
            var draft=draft(tx,request.draftId());if(draft.revision()!=request.expectedRevision()||request.exampleIndex()>=draft.definition().examples().size())throw Failure.conflict();BuilderValidation.validate(codec,draft.definition(),true);
            var device=tx.endpoint(request.deviceId());if(device==null)throw forbidden();endpoints.active(tx,codec.model(device.document(),EndpointDeviceRecord.class));if(tx.builder().count(TEST)>=256)throw Failure.conflict();
            var job=new BuilderTestRecord(request.id(),draft.id(),draft.definitionDigest(),request.deviceId(),BuilderTestState.QUEUED,1L,now,now+600000,0L,UUID.randomUUID().toString(),request.exampleIndex(),null);
            tx.builder().save(TEST,new BuilderStore.Row(job.id(),1,codec.json(job)),0);tx.audit(actor.id(),"BUILDER_TEST",job.id(),1,requestId,digest);var response=reply(job,1);tx.remember(actor.id(),key,digest,response);return response;});
    }
    private BuilderTestRecord with(BuilderTestRecord job,BuilderTestState state,long expires,long attempt,ErrorCode error){return new BuilderTestRecord(job.id(),job.draftId(),job.definitionDigest(),job.deviceId(),state,job.revision()+1,job.createdAtUnixMs(),expires,attempt,job.leaseId(),job.exampleIndex(),error);}
    private void put(Store.Session tx,BuilderTestRecord old,BuilderTestRecord next){tx.builder().save(TEST,new BuilderStore.Row(next.id(),next.revision(),codec.json(next)),old.revision());}
    public Store.Reply tests(DirectoryService.Actor actor,String cursor){admin(actor);if(cursor!=null)Ids.valid(cursor);return store.transaction(tenant,false,tx->{long now=clock.millis();var rows=tx.builder().page(TEST,cursor==null?"":cursor,33);return reply(new BuilderTestPage(rows.stream().limit(32).map(r->{var job=codec.model(r.document(),BuilderTestRecord.class);permission(tx,actor,"read",draft(tx,job.draftId()).definition());endpoints.management(tx,actor,"read",job.deviceId());return (job.state()==BuilderTestState.QUEUED||job.state()==BuilderTestState.RUNNING)&&job.expiresAtUnixMs()<=now?with(job,BuilderTestState.EXPIRED,job.expiresAtUnixMs(),job.attempt(),ErrorCode.TIMEOUT):job;}).toList(),rows.size()>32?rows.get(31).id():null),0);});}
    public Store.Reply poll(X509Certificate peer,String requestId){available();Ids.valid(requestId);return store.transaction(tenant,true,tx->{long now=now(tx);var device=endpoints.authenticate(tx,peer,now);
        for(var row:jobs(tx)){var job=codec.model(row.document(),BuilderTestRecord.class);if(!job.deviceId().equals(device.deviceId())||job.state()!=BuilderTestState.QUEUED&&job.state()!=BuilderTestState.RUNNING)continue;
            if(job.expiresAtUnixMs()<=now){var expired=with(job,BuilderTestState.EXPIRED,job.expiresAtUnixMs(),job.attempt(),ErrorCode.TIMEOUT);put(tx,job,expired);tx.audit(device.keyFingerprint(),"BUILDER_RESULT",job.id(),expired.revision(),requestId,job.definitionDigest());continue;}
            var draft=draft(tx,job.draftId());if(!draft.definitionDigest().equals(job.definitionDigest())){var failed=with(job,BuilderTestState.FAILED,job.expiresAtUnixMs(),job.attempt(),ErrorCode.CONFLICT);put(tx,job,failed);tx.audit(device.keyFingerprint(),"BUILDER_RESULT",job.id(),failed.revision(),requestId,job.definitionDigest());continue;}
            if(job.state()==BuilderTestState.QUEUED){var running=with(job,BuilderTestState.RUNNING,Math.min(job.expiresAtUnixMs(),now+120000),1, null);put(tx,job,running);job=running;tx.audit(device.keyFingerprint(),"BUILDER_LEASE",job.id(),job.revision(),requestId,job.definitionDigest());}
            return reply(new BuilderTestPoll(crypto.builder(new BuilderTestTask(1L,tenant.value(),server,device.deviceId(),job,draft.definition(),job.expiresAtUnixMs()))),job.revision());}
        return reply(new BuilderTestPoll(null),0);});}
    public Store.Reply result(X509Certificate peer,String body,String requestId){available();Ids.valid(requestId);var request=codec.model(body,BuilderTestResult.class);return store.transaction(tenant,true,tx->{long now=now(tx);var device=endpoints.authenticate(tx,peer,now);var row=tx.builder().get(TEST,request.jobId());if(row==null)throw forbidden();var job=codec.model(row.document(),BuilderTestRecord.class);
        if(!job.deviceId().equals(device.deviceId())||!job.leaseId().equals(request.leaseId())||!job.definitionDigest().equals(request.definitionDigest()))throw forbidden();
        var state=request.success()?BuilderTestState.PASSED:BuilderTestState.FAILED;var error=request.success()?null:request.error();if(!request.success()&&error==null||request.success()&&request.error()!=null)throw Failure.validation();
        if(job.state()==state&&job.error()==error)return reply(job,job.revision());if(job.state()!=BuilderTestState.RUNNING||job.expiresAtUnixMs()<=now)throw Failure.conflict();
        if(!draft(tx,job.draftId()).definitionDigest().equals(job.definitionDigest()))throw Failure.conflict();var complete=with(job,state,job.expiresAtUnixMs(),job.attempt(),error);put(tx,job,complete);tx.audit(device.keyFingerprint(),"BUILDER_RESULT",job.id(),complete.revision(),requestId,job.definitionDigest());return reply(complete,complete.revision());});}
    public Store.Reply seal(DirectoryService.Actor actor,String id,String body,String key,String requestId){admin(actor);Ids.valid(key);Ids.valid(requestId);var request=codec.model(body,BuilderRevisionRequest.class);var digest=DirectoryService.digest("builder.seal\n"+id+"\n"+body);return store.transaction(tenant,true,tx->{now(tx);permission(tx,actor,"build",draft(tx,id).definition());var replay=tx.replay(actor.id(),key,digest);if(replay!=null)return replay;var draft=draft(tx,id);if(draft.sealed()||draft.revision()!=request.expectedRevision())throw Failure.conflict();BuilderValidation.validate(codec,draft.definition(),true);
        var passed=new HashSet<Long>();for(var row:jobs(tx)){var job=codec.model(row.document(),BuilderTestRecord.class);if(job.state()==BuilderTestState.PASSED&&job.definitionDigest().equals(draft.definitionDigest()))passed.add(job.exampleIndex());}for(long index=0;index<draft.definition().examples().size();index++)if(!passed.contains(index))throw Failure.conflict();
        var sealed=new BuilderDraft(draft.id(),draft.revision()+1,draft.definition(),draft.definitionDigest(),true,draft.packageDocument());tx.builder().save(VERSION,new BuilderStore.Row(DirectoryService.digest(draft.definition().packageId()+"\n"+draft.definition().version()),1,codec.json(sealed)),0);tx.builder().save(DRAFT,new BuilderStore.Row(id,sealed.revision(),codec.json(sealed)),draft.revision());tx.audit(actor.id(),"BUILDER_SEAL",id,sealed.revision(),requestId,digest);var response=reply(sealed,sealed.revision());tx.remember(actor.id(),key,digest,response);return response;});}
    public Store.Reply publication(DirectoryService.Actor actor,String id,String requestId){admin(actor);Ids.valid(requestId);return store.transaction(tenant,true,tx->{now(tx);var draft=draft(tx,id);permission(tx,actor,"read",draft.definition());if(!draft.sealed())throw Failure.conflict();BuilderValidation.validate(codec,draft.definition(),true);tx.audit(actor.id(),"BUILDER_EXPORT",id,draft.revision(),requestId,draft.definitionDigest());return reply(draft.definition(),draft.revision());});}
    public Store.Reply publish(DirectoryService.Actor actor,String id,String body,String key,String requestId){admin(actor);var draft=store.transaction(tenant,false,tx->draft(tx,id));if(!draft.sealed())throw Failure.conflict();var release=codec.model(body,FleetPackageRelease.class);var verified=crypto.release(release.release());if(!draft.packageDocument().equals(verified.model()))throw forbidden();return fleet.publish(actor,body,key,requestId);}
    public Store.Reply deploy(DirectoryService.Actor actor,String id,String body,String key,String requestId){admin(actor);var draft=store.transaction(tenant,false,tx->draft(tx,id));if(!draft.sealed())throw Failure.conflict();var request=codec.model(body,FleetRolloutRequest.class);if(!request.packageId().equals(draft.definition().packageId())||!request.version().equals(draft.definition().version()))throw forbidden();fleet.requireRelease(actor,draft.packageDocument());return fleet.rollout(actor,body,key,requestId);}
}
