// Copyright 2026 OLO Labs
// SPDX-License-Identifier: Apache-2.0
import {useEffect,useState} from 'react';
import type {EnterpriseEffectiveAccess} from '@olo-labs/toolgate-contracts';
import {ControlClient,ApiError} from './api';
import {Failure} from './Failure';
/** Read-only inherited tuples never appear as permissions attached to the individual. */
export function EffectiveAccess({client,entity,id}:{client:ControlClient;entity:'users'|'agents'|'tools'|'devices';id:string}){
 const [value,setValue]=useState<EnterpriseEffectiveAccess>(),[error,setError]=useState<unknown>(),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const abort=new AbortController();setValue(undefined);setError(undefined);client.effectiveAccess(entity,id,abort.signal).then(result=>{if(!Array.isArray(result.memberships)||!Array.isArray(result.bindings)||!Array.isArray(result.managementRoles)||!result.memberships.every(m=>Array.isArray(m.roleIds)&&Array.isArray(m.grants)))throw new ApiError(502,'INVALID_RESPONSE');if(!abort.signal.aborted)setValue(result);}).catch(failure=>{if(!abort.signal.aborted)setError(failure);});return()=>abort.abort();},[client,entity,id,attempt]);
 return <section aria-label="Inherited access provenance"><div className="page-heading"><h2>Inherited access</h2><button onClick={()=>setAttempt(attempt+1)}>Refresh inherited access</button></div><p>These complete rules come from groups and Roles. Execution also requires an enabled binding, verified identity, current device trust, resource extraction, all conditions and any independent approval.</p>{error!==undefined&&<Failure error={error}/>} {!value&&!error&&<p role="status">Loading current group provenance…</p>}{value&&<><p>Directory revision {value.directoryRevision} · authorization epoch {value.authorizationEpoch}</p>{value.memberships.map(m=><article key={m.groupId}><h3>{m.groupType}: {m.groupId} · {m.enabled?'Enabled':'Disabled'}</h3><p>Group Roles: {m.roleIds.join(', ')||'None'}</p>{m.grants.length?<div className="table-wrap inherited-scopes" role="region" aria-label={"Complete scopes for "+m.groupId} tabIndex={0}><table><caption>Complete candidate scopes from {m.groupId}</caption><thead><tr><th>Grant / source</th><th>Purpose</th><th>Tool / Device Groups</th><th>Actions / resources / conditions</th></tr></thead><tbody>{m.grants.map(g=><tr key={g.id}><td>{g.id}<br/>{g.sourceType}: {g.sourceId} · {g.enabled?'Enabled':'Disabled'}</td><td>{g.purpose}</td><td>{g.scope.toolGroups.all?'All Tool Groups':g.scope.toolGroups.ids.join(', ')||'No Tool Groups'}<br/>{g.scope.deviceGroups.all?'All Device Groups':g.scope.deviceGroups.ids.join(', ')||'No Device Groups'}</td><td>{g.scope.allActions?'All actions':g.scope.actions.join(', ')||'No actions'}<details><summary>Resources and conditions</summary><pre>{JSON.stringify({resources:g.scope.resources,conditions:g.scope.conditions},null,2)}</pre></details></td></tr>)}</tbody></table></div>:<p>No group grant paths.</p>}</article>)}<h3>Execution bindings</h3>{value.bindings.length?<ul>{value.bindings.map(b=><li key={b.id}>{b.id}: {b.toolGroupId} → {b.deviceGroupId} · {b.enabled?'Enabled':'Disabled'} · {b.actions.join(', ')}</li>)}</ul>:<p>No visible execution bindings.</p>}{value.managementRoles.length>0&&<><h3>Group Management Roles</h3>{value.managementRoles.map(r=><details key={r.id}><summary>{r.name} ({r.id}) · {r.enabled?'Enabled':'Disabled'}</summary><pre>{JSON.stringify(r.managementRules,null,2)}</pre></details>)}</>}</>}</section>;
}
