// Copyright 2026 OLO Labs
// SPDX-License-Identifier: Apache-2.0
import {useEffect,useRef,useState} from 'react';
import type {EnterpriseDecision,EnterpriseEvaluation,EnterpriseInvocation,EnterpriseInvocationPage,EnterpriseReconciliation,EnterpriseReconciliationRequest} from '@olo-labs/toolgate-contracts';
import {ControlClient,ApiError} from './api';
import {Failure} from './Failure';

export function EffectOutcomes({client}:{client:ControlClient}){
 const [page,setPage]=useState<EnterpriseInvocationPage>();const [error,setError]=useState<unknown>();const [cursor,setCursor]=useState<string>();const [history,setHistory]=useState<(string|undefined)[]>([]);const [attempt,setAttempt]=useState(0);const [selected,setSelected]=useState<EnterpriseInvocation>();
 const transition=useRef<{body:string;key:string}|undefined>(undefined);const decisionLock=useRef(false);
 const [reviewId,setReviewId]=useState('');const [review,setReview]=useState<EnterpriseReconciliation>();const [busy,setBusy]=useState(false);const [confirmed,setConfirmed]=useState(false);
 useEffect(()=>{const abort=new AbortController();setPage(undefined);setError(undefined);void client.invocations(cursor,abort.signal).then(value=>{if(!abort.signal.aborted)setPage(value);}).catch(e=>{if(!abort.signal.aborted)setError(e);});return()=>abort.abort();},[client,cursor,attempt]);
 const lookup=async()=>{setBusy(true);setError(undefined);try{setReview(await client.outcomeReconciliation(reviewId));setConfirmed(false);}catch(e){setError(e);}finally{setBusy(false);}};
 const decide=async(approve:boolean)=>{if(!review||decisionLock.current)return;decisionLock.current=true;const body={expectedRevision:review.revision,approve};const encoded=JSON.stringify(body);if(transition.current?.body!==encoded)transition.current={body:encoded,key:crypto.randomUUID()};setBusy(true);setError(undefined);try{setReview(await client.decideOutcome(review.id,body,transition.current.key));setAttempt(n=>n+1);transition.current=undefined;}catch(e){setError(e);}finally{decisionLock.current=false;setBusy(false);}};
 return <><div className="page-heading"><h1>Effect outcomes</h1><button onClick={()=>setAttempt(n=>n+1)}>Refresh outcomes</button></div><p>Expired running effects remain unknown until downstream evidence is reviewed. Reconciliation records the outcome and keeps the consumed permit fenced.</p>
 {Boolean(error)&&<Failure error={error} retry={()=>setAttempt(n=>n+1)}/>}{!page&&!error&&<p role="status">Loading outcomes…</p>}
 {page&&<><div className="table-wrap"><table><caption className="sr-only">Invocations in your group scope</caption><thead><tr><th>Invocation</th><th>Tool</th><th>Target</th><th>State</th><th>Completed resources</th></tr></thead><tbody>{page.items.map(i=><tr key={i.id}><th scope="row"><button className="record-link" onClick={()=>setSelected(i)}>{i.id}</button></th><td>{i.evaluation.toolId}</td><td>{i.evaluation.context.deviceId}</td><td>{i.state}</td><td>{i.completedResources.length} / {i.evaluation.resources.length}</td></tr>)}</tbody></table></div>{page.items.length===0&&<p>No invocations in your current scope.</p>}<div className="pagination"><button disabled={!history.length} onClick={()=>{setCursor(history.at(-1));setHistory(history.slice(0,-1));}}>Previous page</button><button disabled={!page.nextCursor} onClick={()=>{setHistory([...history,cursor]);setCursor(page.nextCursor);}}>Next page</button></div></>}
 {selected&&<OutcomeProposal key={selected.id} client={client} invocation={selected} onClose={()=>setSelected(undefined)} onProposed={value=>{setReview(value);setReviewId(value.id);setSelected(undefined);setConfirmed(false);}}/>}
 <section className="guidance"><h2>Review reconciliation evidence</h2><form onSubmit={e=>{e.preventDefault();void lookup();}}><label>Reconciliation ID<input value={reviewId} onChange={e=>setReviewId(e.target.value)} required maxLength={128}/></label><button disabled={busy||!reviewId}>Load review</button></form>
 {review&&<><dl><dt>Invocation</dt><dd>{review.invocationId}</dd><dt>Proposed by</dt><dd>{review.requesterUserId}</dd><dt>Proposed outcome</dt><dd>{review.request.state}</dd><dt>External evidence digest</dt><dd><code>{review.request.evidenceDigest}</code></dd><dt>Exact proposal digest</dt><dd><code>{review.requestDigest}</code></dd><dt>Review state</dt><dd>{review.state}</dd></dl><ul>{review.request.completedResources.map((r,n)=><li key={n}>{r.kind}: {r.locator}</li>)}</ul>{review.state==='PENDING'&&<fieldset disabled={busy}><legend>Independent downstream review</legend><label className="checkbox"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I independently verified the downstream evidence and completed resources.</label><button disabled={!confirmed} onClick={()=>{void decide(true);}}>Approve reconciliation</button><button disabled={!confirmed} onClick={()=>{void decide(false);}}>Deny reconciliation</button></fieldset>}</>}
 </section></>;
}
function OutcomeProposal({client,invocation:i,onClose,onProposed}:{client:ControlClient;invocation:EnterpriseInvocation;onClose:()=>void;onProposed:(v:EnterpriseReconciliation)=>void}){
 const [state,setState]=useState<EnterpriseReconciliationRequest['state']>('FAILED');const [evidence,setEvidence]=useState('');const [result,setResult]=useState('');const [done,setDone]=useState<string[]>(i.completedResources.map(r=>r.kind+'\n'+r.locator));const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);const pending=useRef<{body:string;key:string}|undefined>(undefined);const locked=useRef(false);
 const submit=async()=>{if(locked.current)return;locked.current=true;setBusy(true);setError(undefined);try{const completed=state==='SUCCEEDED'?i.evaluation.resources:state==='FAILED'?[]:i.evaluation.resources.filter(r=>done.includes(r.kind+'\n'+r.locator));const body={expectedRevision:i.revision,state,completedResources:completed,evidenceDigest:evidence,...(result?{resultDigest:result}:{})};const encoded=JSON.stringify(body);if(pending.current?.body!==encoded)pending.current={body:encoded,key:crypto.randomUUID()};onProposed(await client.proposeOutcome(i.id,body,pending.current.key));}catch(e){setError(e);}finally{locked.current=false;setBusy(false);}};
 return <section className="guidance"><h2>Inspect effect {i.id}</h2><p>State: {i.state}. Revision: {i.revision}. Arguments digest: <code>{i.evaluation.argumentsDigest}</code>.</p><button onClick={onClose}>Close inspection</button>{i.state==='OUTCOME_UNKNOWN'&&<form onSubmit={e=>{e.preventDefault();void submit();}}><fieldset disabled={busy}><legend>Propose verified downstream outcome</legend><label>Outcome<select value={state} onChange={e=>setState(e.target.value as typeof state)}><option value="FAILED">Failed without effects</option><option value="SUCCEEDED">Every resource completed</option><option value="PARTIAL">Some resources completed</option></select></label><label>External evidence SHA-256<input required pattern="[a-f0-9]{64}" maxLength={64} value={evidence} onChange={e=>setEvidence(e.target.value)}/></label><label>Result SHA-256<input required={state==='SUCCEEDED'} pattern="[a-f0-9]{64}" maxLength={64} value={result} onChange={e=>setResult(e.target.value)}/></label>{state==='PARTIAL'&&i.evaluation.resources.map((r,n)=>{const id=r.kind+'\n'+r.locator;return <label key={n} className="checkbox"><input type="checkbox" checked={done.includes(id)} onChange={e=>setDone(e.target.checked?[...done,id]:done.filter(x=>x!==id))}/>{r.kind}: {r.locator}</label>;})}<button>Submit reconciliation for independent review</button></fieldset></form>}{Boolean(error)&&<Failure error={error} retry={()=>{void submit();}}/>}</section>;
}
export function AccessSimulation({client}:{client:ControlClient}){
 const [input,setInput]=useState('');const [result,setResult]=useState<EnterpriseDecision>();const [error,setError]=useState<unknown>();const [busy,setBusy]=useState(false);
 const sample=async()=>{setBusy(true);setError(undefined);try{const page=await client.invocations();if(!page.items.length)throw new ApiError(404,'NOT_FOUND');const status=await client.authorityStatus();setInput(JSON.stringify({...page.items[0].evaluation,nowUnixMs:Date.now(),authorityRevision:status.directoryRevision,online:true},null,2));}catch(e){setError(e);}finally{setBusy(false);}};
 const simulate=async()=>{setBusy(true);setError(undefined);setResult(undefined);try{let value:EnterpriseEvaluation;try{value=JSON.parse(input) as EnterpriseEvaluation;}catch{throw new ApiError(400,'INVALID_JSON');}setResult(await client.simulateAccess(value));}catch(e){setError(e);}finally{setBusy(false);}};
 return <><div className="page-heading"><h1>Access simulation</h1></div><p>Evaluate complete current group paths without executing a tool, revealing a secret or consuming an approval or quota.</p><button disabled={busy} onClick={()=>{void sample();}}>Use a recent invocation as a starting point</button><form onSubmit={e=>{e.preventDefault();void simulate();}}><label>Complete evaluation JSON<textarea value={input} onChange={e=>setInput(e.target.value)} rows={18} required maxLength={65536}/></label><button disabled={busy||!input}>Evaluate access</button></form>{Boolean(error)&&<Failure error={error} retry={()=>{void simulate();}}/>}{result&&<section className="guidance"><h2>{result.decision}</h2><p>Reason: {result.reason}. Diagnostic ID: <code>{result.diagnosticId}</code>.</p><pre>{JSON.stringify(result.witnesses,null,2)}</pre>{result.obligations.length>0&&<p>Approval obligations: {result.obligations.join(', ')}</p>}</section>}</>;
}
